dist: jammy
language: php
php:
  - '8.2'
services:
  - mysql
  - postgresql
before_install:
  - sudo cp $TRAVIS_BUILD_DIR/travis-mysql.cnf /etc/mysql/conf.d/
  - sudo service mysql restart
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS kininteltest';
  - sudo mysql -e "CREATE USER 'kininteltest'@'%' identified by 'kininteltest'";
  - sudo mysql -e "GRANT ALL ON kininteltest.* to 'kininteltest'@'%'";
  - sudo service postgresql restart
before_script:
  - sudo psql -c "create user kininteltest with password 'kininteltest' CREATEDB;" -U postgres
  - sudo psql -c 'create database kininteltest;' -U postgres
  - composer clearcache; composer install; composer update;  cd php/test
script: ../../vendor/bin/phpunit .
