<?php

namespace Kinintel\Test\Services\Util\Analysis\TextAnalysis\Extractors;

use Kinintel\Services\Util\Analysis\TextAnalysis\Extractors\DocxTextExtractor;

include_once "autoloader.php";

class DocxTextExtractorTest extends \PHPUnit\Framework\TestCase {

    private $docxExtractor;

    public function setUp(): void {
        $this->docxExtractor = new DocxTextExtractor();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanExtractTextFromDocxString() {
        $string = file_get_contents(__DIR__ . "/test.docx");

        $output = $this->docxExtractor->extractTextFromString($string);

        $this->assertEquals("Hello Docx Test", $output);
    }

    public function testCanExtractTextFromDocxFile() {
        $file = __DIR__ . "/test.docx";

        $output = $this->docxExtractor->extractTextFromFile($file);

        $this->assertEquals("Hello Docx Test", $output);
    }

}
