<?php

namespace Kinintel\Test\Services\Util\Analysis\TextAnalysis\Extractors;

use Kinintel\Services\Util\Analysis\TextAnalysis\Extractors\HTMLTextExtractor;

include_once "autoloader.php";

class HTMLTextExtractorTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var HTMLTextExtractor
     */
    private $htmlExtractor;

    public function setUp(): void {
        $this->htmlExtractor = new HTMLTextExtractor();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanExtractTextFromHTMLString() {
        $htmlString = "<div class='test'><p>Hello World</p></div>";

        $output = $this->htmlExtractor->extractTextFromString($htmlString);

        $this->assertEquals("Hello World", $output);
    }

    public function testCanExtractTextFromHTMLFile() {
        $file = __DIR__ . "/test.html";

        $output = $this->htmlExtractor->extractTextFromFile($file);

        $this->assertEquals("Hello World", $output);
    }

}
