<?php

namespace Kinintel\Test\Services\Util\Analysis\TextAnalysis\Extractors;

use Kinintel\Services\Util\Analysis\TextAnalysis\Extractors\TextTextExtractor;

include_once "autoloader.php";

class TextTextExtractorTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var TextTextExtractor
     */
    private $textExtractor;

    public function setUp(): void {
        $this->textExtractor = new TextTextExtractor();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanExtractTextFromString() {

        $string = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";

        $output = $this->textExtractor->extractTextFromString($string);

        $this->assertEquals($string, $output);

    }

    public function testCanExtractTextFromFile() {

        $filePath = __DIR__ . "/test.txt";

        $output = $this->textExtractor->extractTextFromFile($filePath);

        $this->assertEquals("Hello World 123", $output);

    }

    public function testCanExtractTextAndChunksFromFile(){
        $text = <<<EOD
Address Allocation for Private Internets

Status of this Memo

   This document specifies an Internet Best Current Practices for the
   Internet Community, and requests discussion and suggestions for
   improvements.  Distribution of this memo is unlimited.

1. Introduction

   For the purposes of this document, an enterprise is an entity
   autonomously operating a network using TCP/IP and in particular
   determining the addressing plan and address assignments within that
   network.

   This document describes address allocation for private internets. The
   allocation permits full network layer connectivity among all hosts
   inside an enterprise as well as among all public hosts of different
   enterprises. The cost of using private internet address space is the
   potentially costly effort to renumber hosts and networks between
   public and private.

2. Motivation

   With the proliferation of TCP/IP technology worldwide, including
   outside the Internet itself, an increasing number of non-connected
   enterprises use this technology and its addressing capabilities for
   sole intra-enterprise communications, without any intention to ever
   directly connect to other enterprises or the Internet itself.
EOD;

        $chunks = $this->textExtractor->extractChunksFromString($text);
        $this->assertTrue(str_contains($chunks[2]->getText(), "Internet Best Current Practices"));
        $this->assertFalse(str_contains($chunks[2]->getText(), "an enterprise is an entity"));
    }

}
