<?php

namespace Kinintel\Test\Services\Util\Analysis\TextAnalysis;

use Kinikit\Core\Configuration\FileResolver;
use Kinikit\Core\DependencyInjection\Container;
use Kinintel\Services\Util\Analysis\TextAnalysis\StopwordManager;

include_once "autoloader.php";

class StopwordManagerTest extends \PHPUnit\Framework\TestCase {

    private $stopwordManager;

    public function setUp(): void {
        $this->stopwordManager = new StopwordManager(Container::instance()->get(FileResolver::class));

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanGetTheListOfStopwordsFromConfigForEnglish() {
        $stopwords = $this->stopwordManager->getStopwordsByLanguage('EN');

        $this->assertTrue(is_array($stopwords));
        $this->assertEquals("a", $stopwords[0]);
        $this->assertEquals("about", $stopwords[1]);
        $this->assertEquals("above", $stopwords[2]);
        $this->assertEquals("after", $stopwords[3]);
        $this->assertEquals("again", $stopwords[4]);
    }

}
