<?php

namespace Kinintel\Test\Services\Util\TextAnalysis\Extractors;

use Kinintel\Services\Util\TextAnalysis\Extractors\PDFTextExtractor;

include_once "autoloader.php";

class PDFTextExtractorTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var PDFTextExtractor
     */
    private $extractor;

    public function setUp(): void {
        $this->extractor = new PDFTextExtractor();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanExtractTextFromPDFString() {
        $string = file_get_contents(__DIR__ . "/test.pdf");

        $output = $this->extractor->extractTextFromString($string);

        $this->assertEquals("Hello Docx Test", $output);
    }

    public function testCanExtractTextFromPDFFile() {
        $file = __DIR__ . "/test.pdf";

        $output = $this->extractor->extractTextFromFile($file);

        $this->assertEquals("Hello Docx Test", $output);
    }

}
