<?php

namespace Kinintel\Test\Services\Util\TextAnalysis\Extractors;

use Kinintel\Services\Util\TextAnalysis\Extractors\TextTextExtractor;

include_once "autoloader.php";

class TextTextExtractorTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var TextTextExtractor
     */
    private $textExtractor;

    public function setUp(): void {
        $this->textExtractor = new TextTextExtractor();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanExtractTextFromString() {

        $string = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";

        $output = $this->textExtractor->extractTextFromString($string);

        $this->assertEquals($string, $output);

    }

    public function testCanExtractTextFromFile() {

        $filePath = __DIR__ . "/test.txt";

        $output = $this->textExtractor->extractTextFromFile($filePath);

        $this->assertEquals("Hello World 123", $output);

    }

}
